name: test-python

on: [push]

jobs:
  build-test-python:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, windows-2022]
        python-version: [
          "3.9.x", 
          "3.10.x", 
          "3.11.x",
          "3.12.x",
          "3.13.x",
        ]
        architecture: [x64]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
        architecture: ${{matrix.architecture}}
    - name: Install library
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test] -v
    - name: Test with coverage
      run: |
        coverage run -m --source=iohinspector unittest discover
        coverage report -m 
    - name: Upload coverage report
      if: ${{ matrix.python-version == 3.12 }}
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
          coverage xml -o cobertura.xml
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report